// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akviaasxvjifmofhexea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdmlhYXN4dmppZm1vZmhleGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzUwMTgsImV4cCI6MjA1NDg1MTAxOH0.ZGU4UyW2R2aDx4pC_FdXoQwAYqkux7zPZ7Bd2tI5YK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);